/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#f8f9ff',
          dim: '#cbdbf5',
          bright: '#f8f9ff',
          'container-lowest': '#ffffff',
          'container-low': '#eff4ff',
          container: '#e5eeff',
          'container-high': '#dce9ff',
          'container-highest': '#d3e4fe',
          variant: '#d3e4fe',
        },
        'on-surface': '#0b1c30',
        'on-surface-variant': '#414754',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: {
          DEFAULT: '#727786',
          variant: '#c1c6d7',
        },
        'surface-tint': '#0059c5',
        primary: {
          DEFAULT: '#0058c3',
          container: '#0070f3',
          fixed: '#d8e2ff',
          'fixed-dim': '#aec6ff',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#aec6ff',
        'on-primary-fixed': '#001a43',
        'on-primary-fixed-variant': '#004397',
        secondary: {
          DEFAULT: '#006d40',
          container: '#8ef5b5',
          fixed: '#91f8b8',
          'fixed-dim': '#74db9d',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#007243',
        'on-secondary-fixed': '#002110',
        'on-secondary-fixed-variant': '#00522f',
        tertiary: {
          DEFAULT: '#b81a23',
          container: '#db3738',
          fixed: '#ffdad7',
          'fixed-dim': '#ffb3ad',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffffff',
        'on-tertiary-fixed': '#410004',
        'on-tertiary-fixed-variant': '#930013',
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
      },
      maxWidth: {
        container: '1200px',
      },
      boxShadow: {
        card: '0px 4px 20px rgba(0, 112, 243, 0.05)',
        floating: '0px 12px 32px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
}
